--partialJobStatus=Work Wizard SQL Views
INSERT INTO afm_flds(table_name,field_name,afm_type,allow_null,comments, data_type,decimals,dep_cols,dflt_val,edit_group,edit_mask, enum_list,is_atxt,max_val,min_val,ml_heading,afm_module, num_format,primary_key,ref_table,review_group,afm_size, sl_heading,string_format,is_tc_traceable) SELECT 'wr','satisfaction_notes',2050,1,'Added for v12',12,0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,'Satisfaction\x0D\x0ANotes',4,0,0,NULL,NULL,500,NULL,40,0 FROM  SYS.DUMMY WHERE NOT EXISTS (SELECT 1 FROM afm_flds WHERE table_name = 'wr' AND field_name = 'satisfaction_notes');

INSERT INTO afm_flds(table_name,field_name,afm_type,allow_null,comments, data_type,decimals,dep_cols,dflt_val,edit_group,edit_mask, enum_list,is_atxt,max_val,min_val,ml_heading,afm_module, num_format,primary_key,ref_table,review_group,afm_size, sl_heading,string_format,is_tc_traceable) SELECT 'wr','satisfaction',2050,1,'Added for v12',5,0,NULL,'0',NULL,NULL,'0;No Rating;5;Exceptional;4;Above Average;3;Average;2;Below Average;1;Poor',0,NULL,NULL,'Satisfaction\x0D\x0ARating',4,0,0,NULL,NULL,12,NULL,25,0 FROM  SYS.DUMMY WHERE NOT EXISTS (SELECT 1 FROM afm_flds WHERE table_name = 'wr' AND field_name = 'satisfaction');

IF NOT EXISTS (SELECT 1 FROM SYSCOLUMN as Z, SYSTABLE as T, SYSDOMAIN AS X WHERE T.table_id = Z.table_id AND T.table_type = 'BASE' AND Z.domain_id = X.domain_id AND T.table_name='wr' and  LCase(Z.column_name)='satisfaction') ALTER TABLE wr ADD satisfaction SMALLINT NULL DEFAULT 0;

IF NOT EXISTS (SELECT 1 FROM SYSCOLUMN as Z, SYSTABLE as T, SYSDOMAIN AS X WHERE T.table_id = Z.table_id AND T.table_type = 'BASE' AND Z.domain_id = X.domain_id AND T.table_name='wr' and  LCase(Z.column_name)='satisfaction_notes') ALTER TABLE wr ADD satisfaction_notes VARCHAR(500) NULL DEFAULT NULL;

INSERT INTO afm_flds(table_name,field_name,afm_type,allow_null,comments, data_type,decimals,dep_cols,dflt_val,edit_group,edit_mask, enum_list,is_atxt,max_val,min_val,ml_heading,afm_module, num_format,primary_key,ref_table,review_group,afm_size, sl_heading,string_format,is_tc_traceable) SELECT 'hwr','satisfaction_notes',2050,1,'Added for v12',12,0,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,'Satisfaction\x0D\x0ANotes',4,0,0,NULL,NULL,500,NULL,40,0 FROM  SYS.DUMMY WHERE NOT EXISTS (SELECT 1 FROM afm_flds WHERE table_name = 'hwr' AND field_name = 'satisfaction_notes');

INSERT INTO afm_flds(table_name,field_name,afm_type,allow_null,comments, data_type,decimals,dep_cols,dflt_val,edit_group,edit_mask, enum_list,is_atxt,max_val,min_val,ml_heading,afm_module, num_format,primary_key,ref_table,review_group,afm_size, sl_heading,string_format,is_tc_traceable) SELECT 'hwr','satisfaction',2050,1,'Added for v12',5,0,NULL,'0',NULL,NULL,'0;No Rating;5;Exceptional;4;Above Average;3;Average;2;Below Average;1;Poor',0,NULL,NULL,'Satisfaction\x0D\x0ARating',4,0,0,NULL,NULL,12,NULL,25,0 FROM  SYS.DUMMY WHERE NOT EXISTS (SELECT 1 FROM afm_flds WHERE table_name = 'hwr' AND field_name = 'satisfaction');

IF NOT EXISTS (SELECT 1 FROM SYSCOLUMN as Z, SYSTABLE as T, SYSDOMAIN AS X WHERE T.table_id = Z.table_id AND T.table_type = 'BASE' AND Z.domain_id = X.domain_id AND T.table_name='hwr' and  LCase(Z.column_name)='satisfaction') ALTER TABLE hwr ADD satisfaction SMALLINT NULL DEFAULT 0;

IF NOT EXISTS (SELECT 1 FROM SYSCOLUMN as Z, SYSTABLE as T, SYSDOMAIN AS X WHERE T.table_id = Z.table_id AND T.table_type = 'BASE' AND Z.domain_id = X.domain_id AND T.table_name='hwr' and  LCase(Z.column_name)='satisfaction_notes') ALTER TABLE hwr ADD satisfaction_notes VARCHAR(500) NULL DEFAULT NULL;

INSERT INTO afm_flds(table_name,field_name,afm_type,allow_null,comments, data_type,decimals,dep_cols,dflt_val,edit_group,edit_mask, enum_list,is_atxt,max_val,min_val,ml_heading,afm_module, num_format,primary_key,ref_table,review_group,afm_size, sl_heading,string_format,is_tc_traceable) SELECT 'afm_groups','ww_preferences',2050,1,'Added for v12',12,0,NULL,NULL,'SYSTEM MGR',NULL,NULL,0,NULL,NULL,'Work Wizard\x0D\x0APreferences',0,0,0,NULL,NULL,5000,NULL,40,0 FROM  SYS.DUMMY WHERE NOT EXISTS (SELECT 1 FROM afm_flds WHERE table_name = 'afm_groups' AND field_name = 'ww_preferences');

IF NOT EXISTS (SELECT 1 FROM SYSCOLUMN as Z, SYSTABLE as T, SYSDOMAIN AS X WHERE T.table_id = Z.table_id AND T.table_type = 'BASE' AND Z.domain_id = X.domain_id AND T.table_name='afm_groups' and  LCase(Z.column_name)='ww_preferences') ALTER TABLE afm_groups ADD ww_preferences VARCHAR(5000) NULL DEFAULT NULL;

IF EXISTS (SELECT 1 FROM sysobjects WHERE name = 'wohwo' AND type = 'V') DROP VIEW wohwo;

CREATE VIEW wohwo AS (SELECT ac_id,bl_id,cost_estimated,cost_labor,cost_other,cost_parts,cost_tools,cost_total,date_assigned,date_closed,date_completed,date_created,date_issued,description,dp_id,dv_id,name_authorized,name_of_contact,name_of_planner,option1,option2,priority,qty_open_wr,time_assigned,time_closed,time_completed,time_created,time_issued,tr_id,wo_id,wo_type,supervisor,work_team_id FROM wo) UNION ALL (SELECT ac_id,bl_id,cost_estimated,cost_labor,cost_other,cost_parts,cost_tools,cost_total,date_assigned,date_closed,date_completed,date_created,date_issued,description,dp_id,dv_id,name_authorized,name_of_contact,name_of_planner,option1,option2,priority,qty_open_wr,time_assigned,time_closed,time_completed,time_created,time_issued,tr_id,wo_id,wo_type,supervisor,work_team_id FROM hwo);

IF EXISTS (SELECT 1 FROM sysobjects WHERE name = 'wrhwr' AND type = 'V') DROP VIEW wrhwr;

CREATE VIEW wrhwr AS (SELECT ac_id,act_labor_hours,activity_log_id,bl_id,cause_type,cf_notes,completed_by,cost_est_labor,cost_est_other,cost_est_parts,cost_est_tools,cost_est_total,cost_labor,cost_other,cost_parts,cost_tools,cost_total,curr_meter_val,date_assigned,date_completed,date_est_completion,date_requested,date_stat_chg,desc_other_costs,description,down_time,dp_id,dv_id,eq_id,est_labor_hours,fl_id,location,msg_delivery_status,option1,option2,phone,pmp_id,pms_id,priority,prob_type,repair_type,requestor,rm_id,satisfaction,satisfaction_notes,status,time_assigned,time_completed,time_requested,time_stat_chg,tr_id,wo_id,wr_id,rsres_id,res_id,rmres_id,vn_id,activity_type,dispatcher,step_status,doc1,manager,doc2,doc3,doc4,site_id,supervisor,date_closed,escalated_completion,time_escalation_completion,time_escalation_response,escalated_response,date_escalation_completion,date_escalation_response,serv_window_days,serv_window_end,serv_window_start,allow_work_on_holidays,work_team_id, (IF status = 'R' THEN 0 ELSE (IF status = 'Rev' THEN 1 ELSE (IF status = 'Rej' THEN 2 ELSE (IF status = 'A' THEN 3 ELSE (IF status = 'AA' THEN 4 ELSE (IF status = 'I' THEN 5 ELSE (IF status IN ( 'HP', 'HA', 'HL') THEN 6 ELSE (IF status = 'S' THEN 7 ELSE (IF status = 'Can' THEN 8 ELSE (IF status = 'Com' THEN 9 ELSE 10 ENDIF) ENDIF) ENDIF) ENDIF) ENDIF) ENDIF) ENDIF) ENDIF) ENDIF) ENDIF) AS status_sort FROM wr) UNION ALL (SELECT ac_id,act_labor_hours,activity_log_id,bl_id,cause_type,cf_notes,completed_by,cost_est_labor,cost_est_other,cost_est_parts,cost_est_tools,cost_est_total,cost_labor,cost_other,cost_parts,cost_tools,cost_total,curr_meter_val,date_assigned,date_completed,date_est_completion,date_requested,date_stat_chg,desc_other_costs,description,down_time,dp_id,dv_id,eq_id,est_labor_hours,fl_id,location,msg_delivery_status,option1,option2,phone,pmp_id,pms_id,priority,prob_type,repair_type,requestor,rm_id,satisfaction,satisfaction_notes,status,time_assigned,time_completed,time_requested,time_stat_chg,tr_id,wo_id,wr_id,rsres_id,res_id,rmres_id,vn_id,activity_type,dispatcher,step_status,doc1,manager,doc2,doc3,doc4,site_id,supervisor,date_closed,escalated_completion,time_escalation_completion,time_escalation_response,escalated_response,date_escalation_completion,date_escalation_response,serv_window_days,serv_window_end,serv_window_start,allow_work_on_holidays,work_team_id, (IF status = 'R' THEN 0 ELSE (IF status = 'Rev' THEN 1 ELSE (IF status = 'Rej' THEN 2 ELSE (IF status = 'A' THEN 3 ELSE (IF status = 'AA' THEN 4 ELSE (IF status = 'I' THEN 5 ELSE (IF status IN ( 'HP', 'HA', 'HL') THEN 6 ELSE (IF status = 'S' THEN 7 ELSE (IF status = 'Can' THEN 8 ELSE (IF status = 'Com' THEN 9 ELSE 10 ENDIF) ENDIF) ENDIF) ENDIF) ENDIF) ENDIF) ENDIF) ENDIF) ENDIF) ENDIF) AS status_sort FROM hwr);

IF EXISTS (SELECT 1 FROM sysobjects WHERE name = 'wrview' AND type = 'V') DROP VIEW wrview;

CREATE VIEW wrview AS (SELECT ac_id,act_labor_hours,activity_log_id,bl_id,cause_type,cf_notes,completed_by,cost_est_labor,cost_est_other,cost_est_parts,cost_est_tools,cost_est_total,cost_labor,cost_other,cost_parts,cost_tools,cost_total,curr_meter_val,date_assigned,date_completed,date_est_completion,date_requested,date_stat_chg,desc_other_costs,description,down_time,dp_id,dv_id,eq_id,est_labor_hours,fl_id,location,msg_delivery_status,option1,option2,phone,pmp_id,pms_id,priority,prob_type,repair_type,requestor,rm_id,satisfaction,satisfaction_notes,status,time_assigned,time_completed,time_requested,time_stat_chg,tr_id,wo_id,wr_id,rsres_id,res_id,rmres_id,vn_id,activity_type,dispatcher,step_status,doc1,manager,doc2,doc3,doc4,site_id,supervisor,date_closed,escalated_completion,time_escalation_completion,time_escalation_response,escalated_response,date_escalation_completion,date_escalation_response,serv_window_days,serv_window_end,serv_window_start,allow_work_on_holidays,work_team_id, (IF status = 'R' THEN 0 ELSE (IF status = 'Rev' THEN 1 ELSE (IF status = 'Rej' THEN 2 ELSE (IF status = 'A' THEN 3 ELSE (IF status = 'AA' THEN 4 ELSE (IF status = 'I' THEN 5 ELSE (IF status IN ( 'HP', 'HA', 'HL') THEN 6 ELSE (IF status = 'S' THEN 7 ELSE (IF status = 'Can' THEN 8 ELSE (IF status = 'Com' THEN 9 ELSE 10 ENDIF) ENDIF) ENDIF) ENDIF) ENDIF) ENDIF) ENDIF) ENDIF) ENDIF) ENDIF) AS status_sort FROM wr) UNION ALL (SELECT ac_id,act_labor_hours,activity_log_id,bl_id,cause_type,cf_notes,completed_by,cost_est_labor,cost_est_other,cost_est_parts,cost_est_tools,cost_est_total,cost_labor,cost_other,cost_parts,cost_tools,cost_total,curr_meter_val,date_assigned,date_completed,date_est_completion,date_requested,date_stat_chg,desc_other_costs,description,down_time,dp_id,dv_id,eq_id,est_labor_hours,fl_id,location,msg_delivery_status,option1,option2,phone,pmp_id,pms_id,priority,prob_type,repair_type,requestor,rm_id,satisfaction,satisfaction_notes,status,time_assigned,time_completed,time_requested,time_stat_chg,tr_id,wo_id,wr_id,rsres_id,res_id,rmres_id,vn_id,activity_type,dispatcher,step_status,doc1,manager,doc2,doc3,doc4,site_id,supervisor,date_closed,escalated_completion,time_escalation_completion,time_escalation_response,escalated_response,date_escalation_completion,date_escalation_response,serv_window_days,serv_window_end,serv_window_start,allow_work_on_holidays,work_team_id, (IF status = 'R' THEN 0 ELSE (IF status = 'Rev' THEN 1 ELSE (IF status = 'Rej' THEN 2 ELSE (IF status = 'A' THEN 3 ELSE (IF status = 'AA' THEN 4 ELSE (IF status = 'I' THEN 5 ELSE (IF status IN ( 'HP', 'HA', 'HL') THEN 6 ELSE (IF status = 'S' THEN 7 ELSE (IF status = 'Can' THEN 8 ELSE (IF status = 'Com' THEN 9 ELSE 10 ENDIF) ENDIF) ENDIF) ENDIF) ENDIF) ENDIF) ENDIF) ENDIF) ENDIF) ENDIF) AS status_sort FROM hwr);

IF EXISTS (SELECT 1 FROM sysobjects WHERE name = 'wrcfhwrcf' AND type = 'V') DROP VIEW wrcfhwrcf;

CREATE VIEW wrcfhwrcf AS (SELECT cf_id,comments,cost_double,cost_estimated,cost_over,cost_straight,cost_total,date_assigned,date_end,date_start,hours_diff,hours_double,hours_est,hours_over,hours_straight,hours_total,msg_delivery_status,status_from_remote_cf,time_assigned,time_end,time_start,work_type,wr_id,scheduled_from_tr_id FROM wrcf) UNION ALL (SELECT cf_id,comments,cost_double,cost_estimated,cost_over,cost_straight,cost_total,date_assigned,date_end,date_start,hours_diff,hours_double,hours_est,hours_over,hours_straight,hours_total,msg_delivery_status,status_from_remote_cf,time_assigned,time_end,time_start,work_type,wr_id,scheduled_from_tr_id FROM hwrcf);

IF EXISTS (SELECT 1 FROM sysobjects WHERE name = 'wrpthwrpt' AND type = 'V') DROP VIEW wrpthwrpt;

CREATE VIEW wrpthwrpt AS (SELECT comments,cost_actual,cost_estimated,date_assigned,debited,part_id,qty_actual,qty_estimated,qty_picked,status,time_assigned,wr_id FROM wrpt) UNION ALL (SELECT comments,cost_actual,cost_estimated,date_assigned,debited,part_id,qty_actual,qty_estimated,qty_picked,status,time_assigned,wr_id FROM hwrpt);

INSERT INTO afm_tbls (table_name,comments,afm_module,title,is_sql_view)  SELECT 'wrhwr','SQL view combining wr and hwr',4,'All Work Requests',1  FROM  SYS.DUMMY WHERE NOT EXISTS (SELECT 1 FROM afm_tbls WHERE table_name = 'wrhwr');

INSERT INTO afm_tbls (table_name,comments,afm_module,title,is_sql_view)  SELECT 'wohwo','SQL view combining wo and hwo',4,'All Work Orders',1  FROM  SYS.DUMMY WHERE NOT EXISTS (SELECT 1 FROM afm_tbls WHERE table_name = 'wohwo');

INSERT INTO afm_tbls (table_name,comments,afm_module,title,is_sql_view)  SELECT 'wrview','SQL view with status_sort',4,'Work Requests',1  FROM  SYS.DUMMY WHERE NOT EXISTS (SELECT 1 FROM afm_tbls WHERE table_name = 'wrview');

INSERT INTO afm_flds ( table_name, field_name,afm_type,allow_null,comments, data_type,decimals,dep_cols,dflt_val,edit_group,edit_mask, enum_list,is_atxt,max_val,min_val,ml_heading,afm_module, num_format,primary_key,ref_table,review_group,afm_size, sl_heading,string_format,is_tc_traceable) SELECT 'wrhwr', field_name,afm_type,allow_null,comments, data_type,decimals,dep_cols,dflt_val,edit_group,edit_mask, enum_list,is_atxt,max_val,min_val,ml_heading,afm_module, num_format,primary_key,ref_table,review_group,afm_size, sl_heading,string_format,is_tc_traceable FROM afm_flds WHERE table_name = 'hwr' AND NOT EXISTS (SELECT 1 FROM afm_flds AS  afm_flds_inner WHERE afm_flds_inner.table_name = 'wrhwr' AND afm_flds_inner.field_name = afm_flds.field_name);

INSERT INTO afm_flds ( table_name, field_name,afm_type,allow_null,comments, data_type,decimals,dep_cols,dflt_val,edit_group,edit_mask, enum_list,is_atxt,max_val,min_val,ml_heading,afm_module, num_format,primary_key,ref_table,review_group,afm_size, sl_heading,string_format,is_tc_traceable) SELECT 'wohwo', field_name,afm_type,allow_null,comments, data_type,decimals,dep_cols,dflt_val,edit_group,edit_mask, enum_list,is_atxt,max_val,min_val,ml_heading,afm_module, num_format,primary_key,ref_table,review_group,afm_size, sl_heading,string_format,is_tc_traceable FROM afm_flds WHERE table_name = 'hwo' AND NOT EXISTS (SELECT 1 FROM afm_flds AS  afm_flds_inner WHERE afm_flds_inner.table_name = 'wohwo' AND afm_flds_inner.field_name = afm_flds.field_name);

INSERT INTO afm_flds ( table_name, field_name,afm_type,allow_null,comments, data_type,decimals,dep_cols,dflt_val,edit_group,edit_mask, enum_list,is_atxt,max_val,min_val,ml_heading,afm_module, num_format,primary_key,ref_table,review_group,afm_size, sl_heading,string_format,is_tc_traceable) SELECT 'wrview', field_name,afm_type,allow_null,comments, data_type,decimals,dep_cols,dflt_val,edit_group,edit_mask, enum_list,is_atxt,max_val,min_val,ml_heading,afm_module, num_format,primary_key,ref_table,review_group,afm_size, sl_heading,string_format,is_tc_traceable FROM afm_flds WHERE table_name = 'wr' AND NOT EXISTS (SELECT 1 FROM afm_flds AS  afm_flds_inner WHERE afm_flds_inner.table_name = 'wrview' AND afm_flds_inner.field_name = afm_flds.field_name);

INSERT INTO afm_flds(table_name,field_name,afm_type,allow_null,comments, data_type,decimals,dep_cols,dflt_val,edit_group,edit_mask, enum_list,is_atxt,max_val,min_val,ml_heading,afm_module, num_format,primary_key,ref_table,review_group,afm_size, sl_heading,string_format,is_tc_traceable) SELECT 'wrview','status_sort',2050,0,'status_sort',5,0,NULL,'0',NULL,NULL,NULL,0,NULL,NULL,'Status\x0D\x0ASort',4,0,0,NULL,NULL,1,NULL,25,0 FROM  SYS.DUMMY WHERE NOT EXISTS (SELECT 1 FROM afm_flds WHERE table_name = 'wrview' AND field_name = 'status_sort');

IF EXISTS (SELECT 1 FROM sysobjects WHERE name = 'wrstat' AND type = 'V') DROP VIEW wrstat;

IF EXISTS (SELECT 1 FROM sysobjects WHERE name = 'wrhwrstat' AND type = 'V') DROP VIEW wrhwrstat;

IF EXISTS (SELECT 1 FROM sysobjects WHERE name = 'wostat' AND type = 'V') DROP VIEW wostat;

IF EXISTS (SELECT 1 FROM sysobjects WHERE name = 'wohwostat' AND type = 'V') DROP VIEW wohwostat;

CREATE VIEW wrstat AS SELECT  YEAR( date_assigned ) || '-' ||  MONTH( date_assigned ) AS perform_date, prob_type, status, (IF status = 'R' THEN 0 ELSE (IF status = 'Rev' THEN 1 ELSE (IF status = 'Rej' THEN 2 ELSE (IF status = 'A' THEN 3 ELSE (IF status = 'AA' THEN 4 ELSE (IF status = 'I' THEN 5 ELSE (IF status IN ( 'HP', 'HA', 'HL') THEN 6 ELSE (IF status = 'S' THEN 7 ELSE (IF status = 'Can' THEN 8 ELSE (IF status = 'Com' THEN 9 ELSE 10 ENDIF) ENDIF) ENDIF) ENDIF) ENDIF) ENDIF) ENDIF) ENDIF) ENDIF) ENDIF) AS status_sort, COUNT(*) AS count_wr, SUM( est_labor_hours ) AS est_labor_sum, SUM( act_labor_hours ) AS act_labor_sum, (SUM(act_labor_hours) - SUM(est_labor_hours)) / COUNT(*) AS avg_labor_dif, SUM( cost_est_total ) AS est_cost_sum, SUM( cost_total ) AS act_cost_sum, (SUM(cost_total) - SUM(cost_est_total)) / COUNT(*) AS avg_cost_dif FROM wr GROUP BY  YEAR( date_assigned ) || '-' ||  MONTH( date_assigned ), prob_type, status;

CREATE VIEW wrhwrstat AS(SELECT  YEAR( date_assigned ) || '-' ||  MONTH( date_assigned ) AS perform_date, prob_type, status, (IF status = 'R' THEN 0 ELSE (IF status = 'Rev' THEN 1 ELSE (IF status = 'Rej' THEN 2 ELSE (IF status = 'A' THEN 3 ELSE (IF status = 'AA' THEN 4 ELSE (IF status = 'I' THEN 5 ELSE (IF status IN ( 'HP', 'HA', 'HL') THEN 6 ELSE (IF status = 'S' THEN 7 ELSE (IF status = 'Can' THEN 8 ELSE (IF status = 'Com' THEN 9 ELSE 10 ENDIF) ENDIF) ENDIF) ENDIF) ENDIF) ENDIF) ENDIF) ENDIF) ENDIF) ENDIF) AS status_sort, COUNT(*) AS count_wr, SUM( est_labor_hours ) AS est_labor_sum, SUM( act_labor_hours ) AS act_labor_sum, (SUM(act_labor_hours) - SUM(est_labor_hours)) / COUNT(*) AS avg_labor_dif, SUM( cost_est_total ) AS est_cost_sum, SUM( cost_total ) AS act_cost_sum, (SUM(cost_total) - SUM(cost_est_total)) / COUNT(*) AS avg_cost_dif FROM wr GROUP BY  YEAR( date_assigned ) || '-' ||  MONTH( date_assigned ), prob_type, status) UNION ALL (SELECT  YEAR( date_assigned ) || '-' ||  MONTH( date_assigned ) AS perform_date, prob_type, status, (IF status = 'R' THEN 0 ELSE (IF status = 'Rev' THEN 1 ELSE (IF status = 'Rej' THEN 2 ELSE (IF status = 'A' THEN 3 ELSE (IF status = 'AA' THEN 4 ELSE (IF status = 'I' THEN 5 ELSE (IF status IN ( 'HP', 'HA', 'HL') THEN 6 ELSE (IF status = 'S' THEN 7 ELSE (IF status = 'Can' THEN 8 ELSE (IF status = 'Com' THEN 9 ELSE 10 ENDIF) ENDIF) ENDIF) ENDIF) ENDIF) ENDIF) ENDIF) ENDIF) ENDIF) ENDIF) AS status_sort, COUNT(*) AS count_wr, SUM( est_labor_hours ) AS est_labor_sum, SUM( act_labor_hours ) AS act_labor_sum, (SUM(act_labor_hours) - SUM(est_labor_hours)) / COUNT(*) AS avg_labor_dif, SUM( cost_est_total ) AS est_cost_sum, SUM( cost_total ) AS act_cost_sum, (SUM(cost_total) - SUM(cost_est_total)) / COUNT(*) AS avg_cost_dif FROM hwr GROUP BY  YEAR( date_assigned ) || '-' ||  MONTH( date_assigned ), prob_type, status);

CREATE VIEW wostat AS SELECT  YEAR( date_assigned ) || '-' ||  MONTH( date_assigned ) AS perform_date, wo_type, tr_id,  IF date_completed IS NULL THEN'Open' ELSE 'Complete' ENDIF AS is_complete, COUNT(*) AS count_wo,  SUM( cost_estimated ) AS est_cost_sum,  SUM( cost_total ) AS act_cost_sum,  (SUM(cost_total) - SUM(cost_estimated)) / COUNT(*) AS avg_cost_dif FROM wo GROUP BY  YEAR( date_assigned ) || '-' ||  MONTH( date_assigned ), wo_type, tr_id,  IF date_completed IS NULL THEN'Open' ELSE 'Complete' ENDIF;

CREATE VIEW wohwostat AS(SELECT  YEAR( date_assigned ) || '-' ||  MONTH( date_assigned ) AS perform_date, wo_type, tr_id,  IF date_completed IS NULL THEN'Open' ELSE 'Complete' ENDIF AS is_complete, COUNT(*) AS count_wo,  SUM( cost_estimated ) AS est_cost_sum,  SUM( cost_total ) AS act_cost_sum,  (SUM(cost_total) - SUM(cost_estimated)) / COUNT(*) AS avg_cost_dif FROM wo GROUP BY  YEAR( date_assigned ) || '-' ||  MONTH( date_assigned ), wo_type, tr_id,  IF date_completed IS NULL THEN'Open' ELSE 'Complete' ENDIF) UNION ALL (SELECT  YEAR( date_assigned ) || '-' ||  MONTH( date_assigned ) AS perform_date, wo_type, tr_id,  IF date_completed IS NULL THEN'Open' ELSE 'Complete' ENDIF AS is_complete, COUNT(*) AS count_wo,  SUM( cost_estimated ) AS est_cost_sum,  SUM( cost_total ) AS act_cost_sum,  (SUM(cost_total) - SUM(cost_estimated)) / COUNT(*) AS avg_cost_dif FROM hwo GROUP BY  YEAR( date_assigned ) || '-' ||  MONTH( date_assigned ), wo_type, tr_id,  IF date_completed IS NULL THEN'Open' ELSE 'Complete' ENDIF);

ALTER TABLE wr MODIFY time_requested TIME NULL DEFAULT CURRENT TIME;